import Ionicons from '@expo/vector-icons/Ionicons';
import { router, useLocalSearchParams } from 'expo-router';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTransactions } from '../../contexts/TransactionsContext';
import { useAppPreferences } from '../../contexts/AppPreferencesContext';

export default function TransactionDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { getTransaction, updateTransaction, deleteTransaction } = useTransactions();
  const transaction = getTransaction(id);
  const [editing, setEditing] = useState(false);
  const [merchant, setMerchant] = useState(transaction?.merchant ?? '');
  const [amount, setAmount] = useState(transaction?.amount.toString() ?? '');
  const [note, setNote] = useState(transaction?.note ?? '');
  const { darkMode } = useAppPreferences();
  const theme = darkMode ? { background: '#0f172a', card: '#1e293b', text: '#f8fafc', muted: '#cbd5e1', line: '#334155' } : { background: '#f8fafc', card: '#fff', text: '#0f172a', muted: '#94a3b8', line: '#e2e8f0' };
  if (!transaction) return <SafeAreaView style={styles.screen}><Text style={styles.title}>Transaction not found</Text><Pressable onPress={() => router.back()}><Text style={styles.link}>Go back</Text></Pressable></SafeAreaView>;
  const save = () => { const numericAmount = Number(amount); if (!merchant.trim() || !numericAmount) return; updateTransaction(transaction.id, { merchant: merchant.trim(), amount: numericAmount, note: note.trim() }); setEditing(false); };
  const remove = () => Alert.alert('Delete transaction?', 'This expense will be removed from this session.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => { deleteTransaction(transaction.id); router.back(); } }]);
  return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={24} color={theme.text} /><Text style={[styles.backText, { color: theme.text }]}>Transaction details</Text></Pressable><View style={[styles.card, { backgroundColor: theme.card }]}><View style={[styles.icon, { backgroundColor: transaction.color + '20' }]}><Ionicons name={transaction.icon as never} size={34} color={transaction.color} /></View>{editing ? <><Text style={[styles.fieldLabel, { color: theme.muted }]}>Merchant</Text><TextInput value={merchant} onChangeText={setMerchant} style={[styles.input, { color: theme.text, backgroundColor: theme.background }]} /><Text style={[styles.fieldLabel, { color: theme.muted }]}>Amount</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" style={[styles.input, { color: theme.text, backgroundColor: theme.background }]} /><Text style={[styles.fieldLabel, { color: theme.muted }]}>Note</Text><TextInput value={note} onChangeText={setNote} style={[styles.input, { color: theme.text, backgroundColor: theme.background }]} /><Pressable onPress={save} style={styles.primaryButton}><Text style={styles.buttonText}>Save changes</Text></Pressable></> : <><Text style={[styles.merchant, { color: theme.text }]}>{transaction.merchant}</Text><Text style={[styles.amount, transaction.category === 'Saving' && styles.savingAmount]}>{transaction.category === 'Saving' ? '+' : '-'}${transaction.amount.toFixed(2)}</Text><View style={[styles.divider, { backgroundColor: theme.line }]} /><DetailRow label="Category" value={transaction.category} theme={theme} /><DetailRow label="Date" value={transaction.date} theme={theme} /><DetailRow label="Note" value={transaction.note || 'No note added'} theme={theme} /><View style={styles.actions}><Pressable onPress={() => setEditing(true)} style={styles.secondaryButton}><Ionicons name="create-outline" size={18} color="#2563eb" /><Text style={styles.secondaryText}>Edit</Text></Pressable><Pressable onPress={remove} style={styles.deleteButton}><Ionicons name="trash-outline" size={18} color="#dc2626" /><Text style={styles.deleteText}>Delete</Text></Pressable></View></>}</View></SafeAreaView>;
}

function DetailRow({ label, value, theme }: { label: string; value: string; theme: { text: string; muted: string } }) { return <View style={styles.detailRow}><Text style={[styles.detailLabel, { color: theme.muted }]}>{label}</Text><Text style={[styles.detailValue, { color: theme.text }]}>{value}</Text></View>; }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#f8fafc', padding: 22 }, back: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 12 }, backText: { color: '#334155', fontWeight: '700', fontSize: 16 }, card: { backgroundColor: '#fff', borderRadius: 24, padding: 22, marginTop: 20, shadowColor: '#0f172a', shadowOpacity: 0.08, shadowRadius: 16, elevation: 3 }, icon: { width: 74, height: 74, borderRadius: 24, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' }, merchant: { textAlign: 'center', color: '#0f172a', fontSize: 24, fontWeight: '800', marginTop: 18 }, amount: { textAlign: 'center', color: '#2563eb', fontSize: 34, fontWeight: '800', marginTop: 8 }, savingAmount: { color: '#14b8a6' }, divider: { height: 1, backgroundColor: '#e2e8f0', marginVertical: 22 }, detailRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 18, paddingVertical: 10 }, detailLabel: { color: '#94a3b8', fontSize: 13 }, detailValue: { flex: 1, textAlign: 'right', color: '#0f172a', fontSize: 15, fontWeight: '700' }, fieldLabel: { fontSize: 13, fontWeight: '700', marginTop: 18, marginBottom: 6 }, input: { borderRadius: 12, padding: 13, fontSize: 16 }, primaryButton: { backgroundColor: '#2563eb', borderRadius: 13, alignItems: 'center', padding: 14, marginTop: 22 }, buttonText: { color: '#fff', fontWeight: '800' }, actions: { flexDirection: 'row', gap: 10, marginTop: 22 }, secondaryButton: { flex: 1, borderRadius: 12, padding: 13, backgroundColor: '#dbeafe', flexDirection: 'row', gap: 7, justifyContent: 'center', alignItems: 'center' }, secondaryText: { color: '#2563eb', fontWeight: '800' }, deleteButton: { flex: 1, borderRadius: 12, padding: 13, backgroundColor: '#fee2e2', flexDirection: 'row', gap: 7, justifyContent: 'center', alignItems: 'center' }, deleteText: { color: '#dc2626', fontWeight: '800' }, title: { color: '#0f172a', fontSize: 25, fontWeight: '800', marginTop: 30 }, link: { color: '#2563eb', fontWeight: '700', marginTop: 12 } });